### ISSUE TITLE
Just try to use this package to open downloaded apk file but it didnot work. 

### ISSUE THREAD

**Issue by arshad-dqot** [joutvhu/open_file_plus#1]
`final result = await OpenFile.open(
            filePath,
          );
          print("type" +
              result.type.toString() +
              "message" +
              result.message.toString());`

Before this I was using open_file which working good enough but have permission of REQUEST_INSTALL_ALL_PACKAGE.

Console:-
`I/flutter (14421): typeResultType.donemessagedone`

**Comment by joutvhu** [comment]
The issues has been fixed by version 3.4.0. 
However, to open the APK file, you need to add `<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES"/>` to your `AndroidManifest.xml` file.
